
import javax.swing.JOptionPane;

/*
 * BinaryToGray.java
 *
 * Created on 2 March, 2020, 3:26 AM
 */



/**
 *
 * @author  KaranRajpara
 */
public class BinaryToGray extends javax.swing.JFrame {
    static int binary[]=new int[8];
    static int gray[]=new int[8];
    /** Creates new form BinaryToGray */
    public BinaryToGray() {
        initComponents();
        setSize(800,540);
        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b1_txt = new javax.swing.JTextField();
        b2_txt = new javax.swing.JTextField();
        b3_txt = new javax.swing.JTextField();
        b4_txt = new javax.swing.JTextField();
        b5_txt = new javax.swing.JTextField();
        b6_txt = new javax.swing.JTextField();
        b7_txt = new javax.swing.JTextField();
        b8_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gray1_txt = new javax.swing.JTextField();
        gray2_txt = new javax.swing.JTextField();
        gray3_txt = new javax.swing.JTextField();
        gray4_txt = new javax.swing.JTextField();
        gray5_txt = new javax.swing.JTextField();
        gray6_txt = new javax.swing.JTextField();
        gray7_txt = new javax.swing.JTextField();
        gray8_txt = new javax.swing.JTextField();
        jButton1_go = new javax.swing.JButton();
        jButton2_Home = new javax.swing.JButton();
        jButton1_next1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Binary To Gray Conversion");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Binary Number");

        b1_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b2_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b3_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b4_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b5_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b6_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b7_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        b8_txt.setFont(new java.awt.Font("SansSerif", 0, 14));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Gray Number");

        jButton1_go.setText("GO");
        jButton1_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_goActionPerformed(evt);
            }
        });

        jButton2_Home.setText("Home");
        jButton2_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_HomeActionPerformed(evt);
            }
        });

        jButton1_next1.setText("NEXT STEP");
        jButton1_next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_next1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18));

        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(b1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(gray1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gray8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jButton1_go, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(217, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1_next1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_go, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_next1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gray1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gray8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_HomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton2_HomeActionPerformed

    private void jButton1_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_goActionPerformed
        // TODO add your handling code here:
       /* int b1,b2,b3,b4,b5,b6,b7,b8=0;
        b1=Integer.parseInt(b1_txt.getText());
        b2=Integer.parseInt(b2_txt.getText());
        b3=Integer.parseInt(b3_txt.getText());
        b4=Integer.parseInt(b4_txt.getText());
        b5=Integer.parseInt(b5_txt.getText());
        b6=Integer.parseInt(b6_txt.getText());
        b7=Integer.parseInt(b7_txt.getText());
        b8=Integer.parseInt(b8_txt.getText());
        
        Logic.binary[0]=b1;
        Logic.binary[1]=b2;
        Logic.binary[2]=b3;
        Logic.binary[3]=b4;
        Logic.binary[4]=b5;
        Logic.binary[5]=b6;
        Logic.binary[6]=b7;
        Logic.binary[7]=b8;*/
        
        int num=Integer.parseInt(jTextField1.getText());
        int i=7,a,count=0;
        int flag=0;
      //  int binary[]=new int[8];
        try{
         while(num>0)
    {
        a=num%10;
        if(a!=1 && a!=0)
        {
            flag=1;
            jTextField1.setText("");
            b1_txt.setText("");
            b2_txt.setText("");
            b3_txt.setText("");
            b4_txt.setText("");
            b5_txt.setText("");
            b6_txt.setText("");
            b7_txt.setText("");
            b8_txt.setText("");
            JOptionPane.showMessageDialog(this, "You have entered invalid number...Enter only 0 and 1"); 
            
          
        }
        binary[i]=a;
        i--;
        count++;
        if(count>8){
             flag=1;
            JOptionPane.showMessageDialog(this, "Length is greater than 8... Please enter number which has less than 8 length");
            jTextField1.setText("");
        }
        num=num/10;

    }
        }catch(Exception e){
            flag=1;
            JOptionPane.showMessageDialog(this, "You have entered invalid number. Enter only 8 digits.");
        }
       if(flag==0){
        b1_txt.setText(Integer.toString(binary[0]));
        b2_txt.setText(Integer.toString(binary[1]));
        b3_txt.setText(Integer.toString(binary[2]));
        b4_txt.setText(Integer.toString(binary[3]));
        b5_txt.setText(Integer.toString(binary[4]));
        b6_txt.setText(Integer.toString(binary[5]));
        b7_txt.setText(Integer.toString(binary[6]));
        b8_txt.setText(Integer.toString(binary[7]));
       }
}//GEN-LAST:event_jButton1_goActionPerformed

    private void jButton1_next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_next1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_next1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int count=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int count=0;
        gray1_txt.setText(Integer.toString(binary[0]));
        gray[0]=binary[0];
                             for(int i=0;i<7;i++)
                            {
				count=0;
				if(binary[i]==1)
				{
					count++;
				}
				if(binary[i+1]==1)
				{
					count++;
				}
				if(count==1)
				{
					gray[i+1]=1;
					
				}
				if(count==2)
				{
					gray[i+1]=0;
				}
			}
        gray2_txt.setText(Integer.toString(gray[1]));
        gray3_txt.setText(Integer.toString(gray[2]));
        gray4_txt.setText(Integer.toString(gray[3]));
        gray5_txt.setText(Integer.toString(gray[4]));
        gray6_txt.setText(Integer.toString(gray[5]));
        gray7_txt.setText(Integer.toString(gray[6]));
        gray8_txt.setText(Integer.toString(gray[7]));
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinaryToGray().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1_txt;
    private javax.swing.JTextField b2_txt;
    private javax.swing.JTextField b3_txt;
    private javax.swing.JTextField b4_txt;
    private javax.swing.JTextField b5_txt;
    private javax.swing.JTextField b6_txt;
    private javax.swing.JTextField b7_txt;
    private javax.swing.JTextField b8_txt;
    private javax.swing.JTextField gray1_txt;
    private javax.swing.JTextField gray2_txt;
    private javax.swing.JTextField gray3_txt;
    private javax.swing.JTextField gray4_txt;
    private javax.swing.JTextField gray5_txt;
    private javax.swing.JTextField gray6_txt;
    private javax.swing.JTextField gray7_txt;
    private javax.swing.JTextField gray8_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_go;
    private javax.swing.JButton jButton1_next1;
    private javax.swing.JButton jButton2_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
