
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Cursor;
import java.awt.Cursor;
import java.awt.Cursor;
import java.awt.event.FocusListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * BinaryToGrayNew.java
 *
 * Created on 25 April, 2020, 4:10 PM
 */
import javax.swing.JTextField;



/**
 *
 * @author  KaranRajpara
 */
public class BinaryToGrayNew extends javax.swing.JFrame {
    
    static int binary[]=new int[8];
    static int gray[]=new int[8];
    static String prevData;
    static int karan=0;
    static String ftitle="";
    static int decimal;
    static int octal;
    static String hex="";
    static int flagHex=0;
    
   
    /** Creates new form BinaryToGrayNew */
    public BinaryToGrayNew() {
        initComponents();
        //setSize(1100,540);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
       
     
        
        karan=0;
        jTextField3.setText(prevData);
        jLabel2.setText(ftitle);
        //display();
         binary[0]=0;
        binary[1]=0;
        binary[2]=0;
        binary[3]=0;
        binary[4]=0;
        binary[5]=0;
        binary[6]=0;
        binary[7]=0;
        
        gray[0]=0;
        gray[1]=0;
        gray[2]=0;
        gray[3]=0;
        gray[4]=0;
        gray[5]=0;
        gray[6]=0;
        gray[7]=0;
       display();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1_go = new javax.swing.JButton();
        b1_txt = new javax.swing.JTextField();
        b2_txt = new javax.swing.JTextField();
        b3_txt = new javax.swing.JTextField();
        b4_txt = new javax.swing.JTextField();
        b5_txt = new javax.swing.JTextField();
        b6_txt = new javax.swing.JTextField();
        b7_txt = new javax.swing.JTextField();
        b8_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        gray1_txt = new javax.swing.JTextField();
        gray2_txt = new javax.swing.JTextField();
        gray3_txt = new javax.swing.JTextField();
        gray4_txt = new javax.swing.JTextField();
        gray5_txt = new javax.swing.JTextField();
        gray6_txt = new javax.swing.JTextField();
        gray7_txt = new javax.swing.JTextField();
        gray8_txt = new javax.swing.JTextField();
        jTextField_Decimal = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField_Hex1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Octal1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(840, 110, 290, 370);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 20, 170, 50);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Decimal Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 190, 32);

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 18));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 590, 210, 30);

        jButton1_go.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton1_go.setText("NEXT");
        jButton1_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_goActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_go);
        jButton1_go.setBounds(260, 400, 90, 40);

        b1_txt.setEditable(false);
        b1_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b1_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b1_txt);
        b1_txt.setBounds(770, 120, 30, 25);

        b2_txt.setEditable(false);
        b2_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b2_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b2_txt);
        b2_txt.setBounds(770, 160, 30, 25);

        b3_txt.setEditable(false);
        b3_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b3_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b3_txt);
        b3_txt.setBounds(770, 200, 30, 25);

        b4_txt.setEditable(false);
        b4_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b4_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b4_txt);
        b4_txt.setBounds(770, 240, 30, 25);

        b5_txt.setEditable(false);
        b5_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b5_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b5_txt);
        b5_txt.setBounds(770, 290, 30, 25);

        b6_txt.setEditable(false);
        b6_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b6_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b6_txt);
        b6_txt.setBounds(770, 360, 30, 25);

        b7_txt.setEditable(false);
        b7_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b7_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b7_txt);
        b7_txt.setBounds(770, 400, 30, 25);

        b8_txt.setEditable(false);
        b8_txt.setFont(new java.awt.Font("SansSerif", 0, 14));
        b8_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(b8_txt);
        b8_txt.setBounds(770, 440, 30, 25);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 28));
        jButton1.setText("Final Answer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 480, 400, 60);

        gray1_txt.setEditable(false);
        gray1_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray1_txt);
        gray1_txt.setBounds(1160, 110, 30, 30);

        gray2_txt.setEditable(false);
        gray2_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray2_txt);
        gray2_txt.setBounds(1160, 150, 30, 30);

        gray3_txt.setEditable(false);
        gray3_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray3_txt);
        gray3_txt.setBounds(1160, 190, 30, 30);

        gray4_txt.setEditable(false);
        gray4_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray4_txt);
        gray4_txt.setBounds(1160, 230, 30, 30);

        gray5_txt.setEditable(false);
        gray5_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray5_txt);
        gray5_txt.setBounds(1160, 290, 30, 30);

        gray6_txt.setEditable(false);
        gray6_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray6_txt);
        gray6_txt.setBounds(1160, 350, 30, 30);

        gray7_txt.setEditable(false);
        gray7_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray7_txt);
        gray7_txt.setBounds(1160, 390, 30, 30);

        gray8_txt.setEditable(false);
        gray8_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(gray8_txt);
        gray8_txt.setBounds(1160, 440, 30, 30);

        jTextField_Decimal.setFont(new java.awt.Font("SansSerif", 0, 18));
        jTextField_Decimal.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Decimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_Decimal);
        jTextField_Decimal.setBounds(270, 130, 210, 30);

        reset_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        reset_btn.setText("RESET");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn);
        reset_btn.setBounds(380, 400, 110, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1160, 620, 90, 50);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Binary Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 330, 171, 32);

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 18));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 330, 210, 30);

        jTextField_Hex1.setFont(new java.awt.Font("SansSerif", 0, 18));
        jTextField_Hex1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Hex1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_Hex1);
        jTextField_Hex1.setBounds(270, 260, 210, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Hex Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 260, 171, 32);

        jTextField_Octal1.setFont(new java.awt.Font("SansSerif", 0, 18));
        jTextField_Octal1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Octal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_Octal1);
        jTextField_Octal1.setBounds(270, 190, 210, 30);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Octal Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 190, 171, 32);

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" TO GRAY CONVERSION");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 20, 440, 48);

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText(" TO GRAY CONVERSION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 20, 440, 48);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Gray Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 580, 151, 50);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1570, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_goActionPerformed
      
        
        if(ftitle.equals("BINARY")){
            if(karan==0){
            karan++;
            }
        }
        
        
        
        
      if(ftitle.equals("DECIMAL")){
          try{
              decimal=Integer.parseInt(jTextField_Decimal.getText());
              if(decimal>255 || decimal<0){
            JOptionPane.showMessageDialog(this, "Please enter number less than 255");
            jTextField_Decimal.setText("");
            jTextField_Decimal.requestFocusInWindow();
             binary[0]=0;
            binary[1]=0;
            binary[2]=0;
            binary[3]=0;
            binary[4]=0;
            binary[5]=0;
            binary[6]=0;
            binary[7]=0;
        }
        int a,tmp=7;
        int num=decimal;
               while(num>0)
               {
                   a=num%2;
                   binary[tmp]=a;
                   tmp--;
                   num=num/2;
               }
        String decimalBinary=Integer.toString(binary[0])+Integer.toString(binary[1])+Integer.toString(binary[2])+Integer.toString(binary[3])+Integer.toString(binary[4])+Integer.toString(binary[5])+Integer.toString(binary[6])+Integer.toString(binary[7]);
       
      
        if(karan==0){
            karan++;
             JOptionPane.showMessageDialog(this, "First we will find it's binary");
        }
          jTextField3.setText(decimalBinary);
        jTextField3.setBackground(Color.GREEN);
        jTextField3.setForeground(Color.BLACK);
          }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid Number entered...");
            jTextField_Decimal.requestFocusInWindow();
             binary[0]=0;
            binary[1]=0;
            binary[2]=0;
            binary[3]=0;
            binary[4]=0;
            binary[5]=0;
            binary[6]=0;
            binary[7]=0;
        }
          
         
      }
        
        
        
        
        if(ftitle.equals("OCTAL")){
            try{
                octal=Integer.parseInt(jTextField_Octal1.getText());
                if(octal>377){
                JOptionPane.showMessageDialog(this, "Please enter number less than 377");
                jTextField_Octal1.setText("");
                jTextField_Octal1.requestFocusInWindow();
                binary[0]=0;
                binary[1]=0;
                binary[2]=0;
                binary[3]=0;
                binary[4]=0;
                binary[5]=0;
                binary[6]=0;
                binary[7]=0;
            }
            int sum=0,n,r,i=0;
            n=octal;
             while(n>0)
   		 {
       			 r=n%10;
        		sum=sum+(r*(int)(Math.pow(8,i)));
        		i++;
       			 n=n/10;
    		}
              int a,tmp=7;
                int num=sum;
                while(num>0)
           {
               a=num%2;
               binary[tmp]=a;
               tmp--;
               num=num/2;
           }
                String octalBinary=Integer.toString(binary[0])+Integer.toString(binary[1])+Integer.toString(binary[2])+Integer.toString(binary[3])+Integer.toString(binary[4])+Integer.toString(binary[5])+Integer.toString(binary[6])+Integer.toString(binary[7]);
                 if(karan==0){
                     karan++;
             JOptionPane.showMessageDialog(this, "Now we will find it's binary");
        }
          jTextField3.setText(octalBinary);
        jTextField3.setBackground(Color.GREEN);
         jTextField3.setForeground(Color.BLACK);
                
            }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid Number entered...");
            jTextField_Octal1.requestFocusInWindow();
            jTextField_Octal1.setText("");
             binary[0]=0;
            binary[1]=0;
            binary[2]=0;
            binary[3]=0;
            binary[4]=0;
            binary[5]=0;
            binary[6]=0;
            binary[7]=0;
        }
        }
        
        
        if(ftitle.equals("HEX")){
            try{
                hex=jTextField_Hex1.getText();
                 String z="";
                 z=hex;
            int sum=0,a=0,j=7;
            String hexBinary="";
            
            for(int i=0;i<=z.length()-1 && z.charAt(i)!='\0';i++)
       		 {
			char ch=z.charAt(i);
                        if((ch>=48 && ch<=57) || (ch>=65 && ch<=70))
                        {
            		if(ch>='0' && ch<='9')
       			 {
           			 sum=sum+((ch-48)*(int)(Math.pow(16,z.length()-1-i)));
        		}
       	 		else
       		 	{
            			sum=sum+((ch-55)*(int)(Math.pow(16,z.length()-1-i)));
       			 }
                        }
                        else{
                            
                        jTextField_Hex1.setText("");
                            b1_txt.setText("");
                            b2_txt.setText("");
                            b3_txt.setText("");
                            b4_txt.setText("");
                            b5_txt.setText("");
                            b6_txt.setText("");
                            b7_txt.setText("");
                            b8_txt.setText("");
                             binary[0]=0;
                            binary[1]=0;
                            binary[2]=0;
                            binary[3]=0;
                            binary[4]=0;
                            binary[5]=0;
                            binary[6]=0;
                            binary[7]=0;
                            flagHex=1;
                           
                            
                            
                            
                        }
                        
                        int index=7;
                             while(sum>0)
                            {
                                    a=sum%2;
                                    binary[index]=a;
                                    sum=sum/2;
                                    index--;
                            }
                              hexBinary=Integer.toString(binary[0])+Integer.toString(binary[1])+Integer.toString(binary[2])+Integer.toString(binary[3])+Integer.toString(binary[4])+Integer.toString(binary[5])+Integer.toString(binary[6])+Integer.toString(binary[7]);
                             
                    }
                           
                            
                            
                        

            
            if(karan==0){
                                 karan++;
                         //JOptionPane.showMessageDialog(this, "Now we will find it's binary");
            
              if(flagHex==1)
              {
                   System.out.println(flagHex);
                            JOptionPane.showMessageDialog(this, "Please Enter Valid Number and Less than FF...");
                            jTextField_Hex1.requestFocusInWindow();
              }
                             if(flagHex==0){
                                 System.out.println(flagHex);
                      jTextField3.setText(hexBinary);
                    jTextField3.setBackground(Color.GREEN);
                     jTextField3.setForeground(Color.BLACK);
                            
                             }
            }
            }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid Number entered...");
            jTextField_Hex1.requestFocusInWindow();
            jTextField_Hex1.setText("");
            jTextField3.setText("");
            jTextField3.setBackground(Color.WHITE);
             binary[0]=0;
            binary[1]=0;
            binary[2]=0;
            binary[3]=0;
            binary[4]=0;
            binary[5]=0;
            binary[6]=0;
            binary[7]=0;
            karan=0;
        }
        }
   
        
    
        
        
        
         if(karan==1){
             if(flagHex==0)
             {
            JOptionPane.showMessageDialog(this, "First we will extract that binary data...");
            b1_txt.setBackground(Color.yellow);
            b2_txt.setBackground(Color.yellow);
            b3_txt.setBackground(Color.yellow);
            b4_txt.setBackground(Color.yellow);
            b5_txt.setBackground(Color.yellow);
            b6_txt.setBackground(Color.yellow);
            b7_txt.setBackground(Color.yellow);
            b8_txt.setBackground(Color.yellow);
            
       
        int i=7,a,count=0;
        int flag=0;
        //  int binary[]=new int[8];
        try{
            int num=Integer.parseInt(jTextField3.getText());
            while(num>0) {
                a=num%10;
                if(a!=1 && a!=0) {
                    flag=1;
                    jTextField3.setText("");
                    b1_txt.setText("");
                    b2_txt.setText("");
                    b3_txt.setText("");
                    b4_txt.setText("");
                    b5_txt.setText("");
                    b6_txt.setText("");
                    b7_txt.setText("");
                    b8_txt.setText("");
                    JOptionPane.showMessageDialog(this, "You have entered invalid number...Enter only 0 and 1");
                    karan=0;
                     b1_txt.setBackground(Color.WHITE);
                     b2_txt.setBackground(Color.WHITE);
                    b3_txt.setBackground(Color.WHITE);
                    b4_txt.setBackground(Color.WHITE);
                    b5_txt.setBackground(Color.WHITE);
                    b6_txt.setBackground(Color.WHITE);
                    b7_txt.setBackground(Color.WHITE);
                    b8_txt.setBackground(Color.WHITE);
                     binary[0]=0;
                    binary[1]=0;
                    binary[2]=0;
                    binary[3]=0;
                    binary[4]=0;
                    binary[5]=0;
                    binary[6]=0;
                    binary[7]=0;
                    
                    gray[0]=0;
                    gray[1]=0;
                    gray[2]=0;
                    gray[3]=0;
                    gray[4]=0;
                    gray[5]=0;
                    gray[6]=0;
                    gray[7]=0;
                    
                    
                }
                binary[i]=a;
                i--;
                count++;
                if(count>8){
                    flag=1;
                    JOptionPane.showMessageDialog(this, "Length is greater than 8... Please enter number which has less than 8 length");
                    karan=0;
                    jTextField3.setText("");
                     b1_txt.setBackground(Color.WHITE);
                    b2_txt.setBackground(Color.WHITE);
                    b3_txt.setBackground(Color.WHITE);
                    b4_txt.setBackground(Color.WHITE);
                    b5_txt.setBackground(Color.WHITE);
                    b6_txt.setBackground(Color.WHITE);
                    b7_txt.setBackground(Color.WHITE);
                    b8_txt.setBackground(Color.WHITE);
                     binary[0]=0;
                    binary[1]=0;
                    binary[2]=0;
                    binary[3]=0;
                    binary[4]=0;
                    binary[5]=0;
                    binary[6]=0;
                    binary[7]=0;
                    
                    gray[0]=0;
                    gray[1]=0;
                    gray[2]=0;
                    gray[3]=0;
                    gray[4]=0;
                    gray[5]=0;
                    gray[6]=0;
                    gray[7]=0;
                }
                num=num/10;
                
            }
        }catch(Exception e){
            flag=1;
            JOptionPane.showMessageDialog(this, "You have entered invalid number. Enter only 8 digits.");
            karan=0;
            jTextField3.setText("");
             b1_txt.setBackground(Color.WHITE);
        b2_txt.setBackground(Color.WHITE);
        b3_txt.setBackground(Color.WHITE);
        b4_txt.setBackground(Color.WHITE);
        b5_txt.setBackground(Color.WHITE);
        b6_txt.setBackground(Color.WHITE);
        b7_txt.setBackground(Color.WHITE);
        b8_txt.setBackground(Color.WHITE);
         binary[0]=0;
        binary[1]=0;
        binary[2]=0;
        binary[3]=0;
        binary[4]=0;
        binary[5]=0;
        binary[6]=0;
        binary[7]=0;
        
        gray[0]=0;
        gray[1]=0;
        gray[2]=0;
        gray[3]=0;
        gray[4]=0;
        gray[5]=0;
        gray[6]=0;
        gray[7]=0;
        }
        if(flag==0){
            b1_txt.setText(Integer.toString(binary[0]));
            b2_txt.setText(Integer.toString(binary[1]));
            b3_txt.setText(Integer.toString(binary[2]));
            b4_txt.setText(Integer.toString(binary[3]));
            b5_txt.setText(Integer.toString(binary[4]));
            b6_txt.setText(Integer.toString(binary[5]));
            b7_txt.setText(Integer.toString(binary[6]));
            b8_txt.setText(Integer.toString(binary[7]));
             karan++;
             
             
             
              int count2=0;
       // gray1_txt.setText(Integer.toString(binary[0]));
        gray[0]=binary[0];
        for(int j=0;j<7;j++) {
            count2=0;
            if(binary[j]==1) {
                count2++;
            }
            if(binary[j+1]==1) {
                count2++;
            }
            if(count2==1) {
                gray[j+1]=1;
                
            }
            if(count2==2) {
                gray[j+1]=0;
            }
        }
        }
       
        }
        
        else if(karan==2){
            JOptionPane.showMessageDialog(this, "Now we will understand GRAY CODE conversion...");
            JOptionPane.showMessageDialog(this, "First element will be as it is... SO "+b1_txt.getText()+" is as it is");
            gray1_txt.setText(Integer.toString(gray[0]));
            gray1_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==3){
            JOptionPane.showMessageDialog(this , "g6 = b7 EXOR b6 SO ans is "+(Integer.toString(gray[1])));
            gray2_txt.setText((Integer.toString(gray[1])));
            gray2_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==4){
             JOptionPane.showMessageDialog(this , "g5 = b6 EXOR b5 SO ans is "+(Integer.toString(gray[2])));
            gray3_txt.setText((Integer.toString(gray[2])));
            gray3_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==5){
            JOptionPane.showMessageDialog(this , "g4 = b5 EXOR b4 SO ans is "+(Integer.toString(gray[3])));
            gray4_txt.setText((Integer.toString(gray[3])));
            gray4_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==6){
            JOptionPane.showMessageDialog(this , "g3 = b4 EXOR b3 SO ans is "+(Integer.toString(gray[4])));
            gray5_txt.setText((Integer.toString(gray[4])));
            gray5_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==7){
            JOptionPane.showMessageDialog(this , "g2 = b3 EXOR b2 SO ans is "+(Integer.toString(gray[5])));
            gray6_txt.setText((Integer.toString(gray[5])));
            gray6_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==8){
            JOptionPane.showMessageDialog(this , "g1 = b2 EXOR b1 SO ans is "+(Integer.toString(gray[6])));
            gray7_txt.setText((Integer.toString(gray[6])));
            gray7_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==9){
            JOptionPane.showMessageDialog(this , "g0 = b1 EXOR b0 SO ans is "+(Integer.toString(gray[7])));
            gray8_txt.setText((Integer.toString(gray[7])));
            gray8_txt.setBackground(Color.CYAN);
            karan++;
        }
        else if(karan==10){
            jTextField2.setText(Integer.toString(gray[0])+Integer.toString(gray[1])+Integer.toString(gray[2])+Integer.toString(gray[3])+Integer.toString(gray[4])+Integer.toString(gray[5])+Integer.toString(gray[6])+Integer.toString(gray[7]));
            jTextField2.setBackground(Color.orange);
        }
         }
    }//GEN-LAST:event_jButton1_goActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(b1_txt.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Input is not selected.. Plz click NEXT button first..");
        }
        else{
     int count=0;
        gray1_txt.setText(Integer.toString(binary[0]));
        gray[0]=binary[0];
        for(int i=0;i<7;i++) {
            count=0;
            if(binary[i]==1) {
                count++;
            }
            if(binary[i+1]==1) {
                count++;
            }
            if(count==1) {
                gray[i+1]=1;
                
            }
            if(count==2) {
                gray[i+1]=0;
            }
        }
        gray2_txt.setText(Integer.toString(gray[1]));
        gray3_txt.setText(Integer.toString(gray[2]));
        gray4_txt.setText(Integer.toString(gray[3]));
        gray5_txt.setText(Integer.toString(gray[4]));
        gray6_txt.setText(Integer.toString(gray[5]));
        gray7_txt.setText(Integer.toString(gray[6]));
        gray8_txt.setText(Integer.toString(gray[7]));
        
        b1_txt.setBackground(Color.YELLOW);
        b2_txt.setBackground(Color.YELLOW);
        b3_txt.setBackground(Color.YELLOW);
        b4_txt.setBackground(Color.YELLOW);
        b5_txt.setBackground(Color.YELLOW);
        b6_txt.setBackground(Color.YELLOW);
        b7_txt.setBackground(Color.YELLOW);
        b8_txt.setBackground(Color.YELLOW);
        
        
        gray1_txt.setBackground(Color.CYAN);
        gray2_txt.setBackground(Color.CYAN);
        gray3_txt.setBackground(Color.CYAN);
        gray4_txt.setBackground(Color.CYAN);
        gray5_txt.setBackground(Color.CYAN);
        gray6_txt.setBackground(Color.CYAN);
        gray7_txt.setBackground(Color.CYAN);
        gray8_txt.setBackground(Color.CYAN);
        
        
      jTextField2.setText(Integer.toString(gray[0])+Integer.toString(gray[1])+Integer.toString(gray[2])+Integer.toString(gray[3])+Integer.toString(gray[4])+Integer.toString(gray[5])+Integer.toString(gray[6])+Integer.toString(gray[7]));
      jTextField2.setBackground(Color.orange);
      
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        karan=0;
        jTextField3.setText("");
        jTextField2.setText("");
        jTextField_Decimal.setText("");
        jTextField_Hex1.setText("");
        jTextField_Octal1.setText("");
        b1_txt.setText("");
        b2_txt.setText("");
        b3_txt.setText("");
        b4_txt.setText("");
        b5_txt.setText("");
        b6_txt.setText("");
        b7_txt.setText("");
        b8_txt.setText("");
        gray1_txt.setText("");
        gray2_txt.setText("");
        gray3_txt.setText("");
        gray4_txt.setText("");
        gray5_txt.setText("");
        gray6_txt.setText("");
        gray7_txt.setText("");
        gray8_txt.setText("");
         binary[0]=0;
        binary[1]=0;
        binary[2]=0;
        binary[3]=0;
        binary[4]=0;
        binary[5]=0;
        binary[6]=0;
        binary[7]=0;
        
        gray[0]=0;
        gray[1]=0;
        gray[2]=0;
        gray[3]=0;
        gray[4]=0;
        gray[5]=0;
        gray[6]=0;
        gray[7]=0;
        b1_txt.setBackground(Color.WHITE);
        b2_txt.setBackground(Color.WHITE);
        b3_txt.setBackground(Color.WHITE);
        b4_txt.setBackground(Color.WHITE);
        b5_txt.setBackground(Color.WHITE);
        b6_txt.setBackground(Color.WHITE);
        b7_txt.setBackground(Color.WHITE);
        b8_txt.setBackground(Color.WHITE);
        gray1_txt.setBackground(Color.WHITE);
        gray2_txt.setBackground(Color.WHITE);
        gray3_txt.setBackground(Color.WHITE);
        gray4_txt.setBackground(Color.WHITE);
        gray5_txt.setBackground(Color.WHITE);
        gray6_txt.setBackground(Color.WHITE);
        gray7_txt.setBackground(Color.WHITE);
        gray8_txt.setBackground(Color.WHITE);
        jTextField2.setBackground(Color.WHITE);
        if(ftitle.equals("DECIMAL")){
            
            jTextField_Decimal.requestFocusInWindow();
            jTextField3.setBackground(Color.WHITE);
            
        }
        if(ftitle.equals("BINARY")){
           
            jTextField3.requestFocusInWindow();
            
        }
         if(ftitle.equals("OCTAL")){
           
            jTextField_Octal1.requestFocusInWindow();
            jTextField3.setBackground(Color.WHITE);
        }
         if(ftitle.equals("HEX")){
           
            jTextField_Hex1.requestFocusInWindow();
            jTextField3.setBackground(Color.WHITE);
        }
        
        
    }//GEN-LAST:event_reset_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void setTitile(String title){
        ftitle=title;
        if(title.equals("DECIMAL")){
            jTextField_Decimal.setBackground(Color.PINK);
            System.out.println("YEs in setTitle");
        }
    }
    
    public void showData(String value){
        //jTextField1.setText(value);
        prevData=value;
       
    }
    public void display(){
        
        if(ftitle.equals("DECIMAL")){
            jTextField_Decimal.setBackground(Color.blue);
            jTextField_Decimal.requestFocusInWindow();
            jTextField_Hex1.setBackground(Color.LIGHT_GRAY);
            jLabel6.setForeground(Color.LIGHT_GRAY);
            jTextField_Octal1.setBackground(Color.LIGHT_GRAY);
            jLabel7.setForeground(Color.LIGHT_GRAY);
            jTextField_Hex1.setEditable(false);
            jTextField_Octal1.setEditable(false);
            jTextField3.setEditable(false);
            
        }
        if(ftitle.equals("BINARY")){
            jTextField3.setBackground(Color.BLUE);
            jTextField3.requestFocusInWindow();
             jTextField_Decimal.setBackground(Color.LIGHT_GRAY);
            jLabel3.setForeground(Color.LIGHT_GRAY);
            jTextField_Hex1.setBackground(Color.LIGHT_GRAY);
            jLabel6.setForeground(Color.LIGHT_GRAY);
            jTextField_Octal1.setBackground(Color.LIGHT_GRAY);
            jLabel7.setForeground(Color.LIGHT_GRAY);
            jTextField_Decimal.setEditable(false);
            jTextField_Hex1.setEditable(false);
            jTextField_Octal1.setEditable(false);
            
        }
         if(ftitle.equals("OCTAL")){
            jTextField_Octal1.setBackground(Color.BLUE);
            jTextField_Octal1.requestFocusInWindow();
            jTextField_Decimal.setBackground(Color.LIGHT_GRAY);
            jLabel3.setForeground(Color.LIGHT_GRAY);
            jTextField_Hex1.setBackground(Color.LIGHT_GRAY);
            jLabel6.setForeground(Color.LIGHT_GRAY);
            jTextField_Decimal.setEditable(false);
            jTextField_Hex1.setEditable(false);
             jTextField3.setEditable(false);
            
        }
         if(ftitle.equals("HEX")){
            jTextField_Hex1.setBackground(Color.BLUE);
            jTextField_Hex1.requestFocusInWindow();
            jTextField_Decimal.setBackground(Color.LIGHT_GRAY);
            jLabel3.setForeground(Color.LIGHT_GRAY);
            jTextField_Octal1.setBackground(Color.LIGHT_GRAY);
            jLabel7.setForeground(Color.LIGHT_GRAY);
            jTextField_Decimal.setEditable(false);
            jTextField_Octal1.setEditable(false);
             jTextField3.setEditable(false);
            
        }
       
    }
    
  
    /**
     * @param args the command line arguments
     */
 
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BinaryToGrayNew().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1_txt;
    private javax.swing.JTextField b2_txt;
    private javax.swing.JTextField b3_txt;
    private javax.swing.JTextField b4_txt;
    private javax.swing.JTextField b5_txt;
    private javax.swing.JTextField b6_txt;
    private javax.swing.JTextField b7_txt;
    private javax.swing.JTextField b8_txt;
    private javax.swing.JTextField gray1_txt;
    private javax.swing.JTextField gray2_txt;
    private javax.swing.JTextField gray3_txt;
    private javax.swing.JTextField gray4_txt;
    private javax.swing.JTextField gray5_txt;
    private javax.swing.JTextField gray6_txt;
    private javax.swing.JTextField gray7_txt;
    private javax.swing.JTextField gray8_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_go;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_Decimal;
    private javax.swing.JTextField jTextField_Hex1;
    private javax.swing.JTextField jTextField_Octal1;
    private javax.swing.JButton reset_btn;
    // End of variables declaration//GEN-END:variables
    
}
