/*
 * Gray.java
 *
 * Created on 26 April, 2020, 10:48 PM
 */



/**
 *
 * @author  KaranRajpara
 */
import java.awt.*;
import javax.swing.JFrame;
public class Gray extends javax.swing.JFrame {
    
    /** Creates new form Gray */
    public Gray() {
        initComponents();
         //setSize(1100,540);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 48));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GRAY CODE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 30, 380, 55);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("easily since only one bit changes its value during any transition between two numbers.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 500, 1160, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("1. Gray Code is an ordering of the binary numeral system such that two successive values differ in only one bit.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 80, 1080, 100);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("5. Gray codes are very useful in the normal sequence of binary numbers generated by the hardware that  may cause an ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 390, 1160, 100);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText(" error or ambiguity during the transition from one number to the next. So, the Gray code can eliminate this problem");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 430, 1150, 100);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1230, 620, 110, 60);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 620, 110, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("2. Gray code is a non-weighted code and reflective code as well.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 150, 1080, 100);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("i.e. It is a unit distance code.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 260, 330, 100);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("3. It is a cyclic code because successive code words in this code differ in one bit position only.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 220, 1080, 100);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("4. Gray codes are widely used in digital communications and some cable TV systems. ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 330, 1080, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new GrayTable().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gray().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
