
import javax.swing.JOptionPane;

/*
 * HexToGray.java
 *
 * Created on 25 April, 2020, 11:40 PM
 */



/**
 *
 * @author  KaranRajpara
 */
public class HexToGray extends javax.swing.JFrame {
    static int binary[]=new int[8];
    static String hex;
    /** Creates new form HexToGray */
    public HexToGray() {
        initComponents();
           setSize(900,540);
        this.setLocationRelativeTo(null);
         binary[0]=0;
        binary[1]=0;
        binary[2]=0;
        binary[3]=0;
        binary[4]=0;
        binary[5]=0;
        binary[6]=0;
        binary[7]=0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        b1_txt = new javax.swing.JTextField();
        b2_txt = new javax.swing.JTextField();
        b3_txt = new javax.swing.JTextField();
        b4_txt = new javax.swing.JTextField();
        b5_txt = new javax.swing.JTextField();
        b6_txt = new javax.swing.JTextField();
        b7_txt = new javax.swing.JTextField();
        b8_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("HEX TO GRAY CONVERSION");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("For Hex to gray, First We have to convert it into Binary");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Hex Number");

        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 24));

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18));
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Binary Number");

        b1_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b2_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b3_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b4_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b5_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b6_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b7_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        b8_txt.setFont(new java.awt.Font("SansSerif", 0, 18));

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18));
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 18));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(342, 342, 342)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(116, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(195, 195, 195)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
        b1_txt.setText("");
        b2_txt.setText("");
        b3_txt.setText("");
        b4_txt.setText("");
        b5_txt.setText("");
        b6_txt.setText("");
        b7_txt.setText("");
        b8_txt.setText("");
        binary[0]=0;
        binary[1]=0;
        binary[2]=0;
        binary[3]=0;
        binary[4]=0;
        binary[5]=0;
        binary[6]=0;
        binary[7]=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            hex=jTextField1.getText();
            String z=hex;
            int sum=0,a=0,j=7;
            for(int i=0;i<=z.length()-1 && z.charAt(i)!='\0';i++)
       		 {
			char ch=z.charAt(i);
                        if((ch>=48 && ch<=57) || (ch>=65 && ch<=70))
                        {
            		if(ch>='0' && ch<='9')
       			 {
           			 sum=sum+((ch-48)*(int)(Math.pow(16,z.length()-1-i)));
        		}
       	 		else
       		 	{
            			sum=sum+((ch-55)*(int)(Math.pow(16,z.length()-1-i)));
       			 }
                        }
                        else{
                            
                            jTextField1.setText("");
                            b1_txt.setText("");
                            b2_txt.setText("");
                            b3_txt.setText("");
                            b4_txt.setText("");
                            b5_txt.setText("");
                            b6_txt.setText("");
                            b7_txt.setText("");
                            b8_txt.setText("");
                             binary[0]=0;
                            binary[1]=0;
                            binary[2]=0;
                            binary[3]=0;
                            binary[4]=0;
                            binary[5]=0;
                            binary[6]=0;
                            binary[7]=0;
                            JOptionPane.showMessageDialog(this, "Please Enter Valid Number and Less than FF...");
                        }

       		 }
            while(sum>0)
        	{
            		a=sum%2;
            		binary[j]=a;
            		sum=sum/2;
            		j--;
        	}
            
        b1_txt.setText(Integer.toString(binary[0]));
        b2_txt.setText(Integer.toString(binary[1]));
        b3_txt.setText(Integer.toString(binary[2]));
        b4_txt.setText(Integer.toString(binary[3]));
        b5_txt.setText(Integer.toString(binary[4]));
        b6_txt.setText(Integer.toString(binary[5]));
        b7_txt.setText(Integer.toString(binary[6]));
        b8_txt.setText(Integer.toString(binary[7]));
        }catch(Exception e){
           
             jTextField1.setText("");
             b1_txt.setText("");
                            b2_txt.setText("");
                            b3_txt.setText("");
                            b4_txt.setText("");
                            b5_txt.setText("");
                            b6_txt.setText("");
                            b7_txt.setText("");
                            b8_txt.setText("");
                             binary[0]=0;
                            binary[1]=0;
                            binary[2]=0;
                            binary[3]=0;
                            binary[4]=0;
                            binary[5]=0;
                            binary[6]=0;
                            binary[7]=0;
                             JOptionPane.showMessageDialog(this, "You have entered Invalid number...");
                           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(b1_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Binary is not generated..");
        }
        else{
         String str=b1_txt.getText()+b2_txt.getText()+b3_txt.getText()+b4_txt.getText()+b5_txt.getText()+b6_txt.getText()+b7_txt.getText()+b8_txt.getText();
        BinaryToGrayNew d=new BinaryToGrayNew();
        d.showData(str);
        JOptionPane.showMessageDialog(this, "Now you will redirect to the Binary To Gray Conversion Page... ");
        new BinaryToGrayNew().setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HexToGray().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1_txt;
    private javax.swing.JTextField b2_txt;
    private javax.swing.JTextField b3_txt;
    private javax.swing.JTextField b4_txt;
    private javax.swing.JTextField b5_txt;
    private javax.swing.JTextField b6_txt;
    private javax.swing.JTextField b7_txt;
    private javax.swing.JTextField b8_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
