
import java.awt.Color;
import javax.naming.BinaryRefAddr;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * Home.java
 *
 * Created on 19 February, 2020, 4:05 AM
 */



/**
 *
 * @author  KaranRajpara
 */
public class Home extends javax.swing.JFrame {
    
    /** Creates new form Home */
    public Home() {
        initComponents();
        //setSize(900,540);
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
         //this.setSize(1920,1000);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.getHSBColor(40, 180, 100));
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 24));
        jButton5.setForeground(new java.awt.Color(0, 0, 153));
        jButton5.setText("GO TO THE CONCEPT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(480, 190, 410, 70);

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 24));
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("BINARY TO GRAY CONVERSION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 350, 410, 70);

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 24));
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("OCTAL  TO GRAY CONVERSION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(170, 550, 430, 70);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 24));
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("HEX TO GRAY CONVERSION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 540, 420, 70);

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 24));
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("DECIMAL TO GRAY CONVERSION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(780, 350, 430, 70);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 54));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" GRAY CODE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 20, 410, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1560, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String str="";
         BinaryToGrayNew d=new BinaryToGrayNew();
        d.showData(str);
        d.setTitile("BINARY");
       
        new BinaryToGrayNew().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BinaryToGrayNew d=new BinaryToGrayNew();
        d.setTitile("DECIMAL");
      //  d.display();
        new BinaryToGrayNew().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BinaryToGrayNew d=new BinaryToGrayNew();
        d.setTitile("OCTAL");
        new BinaryToGrayNew().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BinaryToGrayNew d=new BinaryToGrayNew();
        d.setTitile("HEX");
        new BinaryToGrayNew().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Gray().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
